apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: devopstool-k8s-deployment
spec:
  selector:
    matchLabels:
      app: devopstool-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: devopstool-k8s
    spec:
      containers:
        - name: devopstool-k8s
          image: shahnawaz312/devopstool-new # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082 # The port that the container is running on in the cluster
