name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Build the Java project using Maven
    - name: Build with Maven
      run: mvn clean package

    # Run tests
    - name: Run Tests
      run: mvn test

    # Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest .

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # Push Docker image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest

    # Log in to Nexus (Artifactory)
    - name: Log in to Nexus Artifactory
      run: echo ${{ secrets.NEXUS_PASSWORD }} | docker login ${{ secrets.NEXUS_URL }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

    # Tag Docker image for Nexus
    - name: Tag Docker Image for Nexus
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest ${{ secrets.NEXUS_URL }}/repository/my-java-app:latest

    # Push Docker image to Nexus Artifactory
    - name: Push Docker Image to Nexus
      run: docker push ${{ secrets.NEXUS_URL }}/repository/my-java-app:latest
